# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKwTiZrRd1SBJ1tX2hA3tuy2-aopyq-8
"""


import streamlit as st
import osmnx as ox
import networkx as nx
import geopandas as gpd
from shapely.geometry import Point
import folium
from streamlit_folium import st_folium
import pandas as pd

# --- KONFIGURASI HALAMAN ---
st.set_page_config(page_title="Bandung Transit Isochrone", layout="wide", page_icon="🗺️")

st.title("🗺️ Analisis Aksesibilitas Multimoda Kota Bandung")
st.markdown("Cari tahu seberapa jauh Anda bisa bepergian. **Klik lokasi mana saja pada peta**, atau pilih Halte TMP dari menu di sebelah kiri!")

# --- 1. LOAD DATA GRAF (DI-CACHE AGAR CEPAT) ---
@st.cache_resource(show_spinner="Memuat jaringan jalan Kota Bandung...")
def load_graph():
    # Pastikan file ini ada di repository GitHub yang sama nantinya
    filepath = "bandung_multimodal_graph.graphml"
    try:
        return ox.load_graphml(filepath)
    except Exception as e:
        st.error(f"Gagal memuat file graf. Error: {e}")
        return None

G_final = load_graph()

# --- 2. DATA HALTE TMP (SAMPEL) ---
# Di dunia nyata, data ini bisa ditarik dari file CSV Dishub.
# Ini adalah sampel beberapa titik strategis jalur Bus & Angkot
halte_data = {
    "Pilih Halte / Lokasi Manual...": None,
    "Halte Alun-Alun Bandung": (-6.9218, 107.6061),
    "Halte Stasiun Bandung": (-6.9143, 107.6022),
    "Terminal Leuwipanjang": (-6.9458, 107.5958),
    "Terminal Cicaheum": (-6.9022, 107.6536),
    "Halte ITB (Ganesha)": (-6.8915, 107.6107),
    "Halte Gedung Sate": (-6.9025, 107.6188),
    "Halte Pasteur (Tol)": (-6.8928, 107.5888)
}

if G_final is not None:
    # --- 3. LAYOUT UI ---
    col1, col2 = st.columns([1, 3])

    with col1:
        st.subheader("📍 Titik Keberangkatan")
        # Dropdown untuk memilih halte
        pilihan_halte = st.selectbox("Pilih Halte TMP Utama:", list(halte_data.keys()))

        st.markdown("---")
        st.subheader("⏱️ Pengaturan Waktu")
        waktu_maksimal = st.slider("Batas Waktu Tempuh (Menit)", min_value=10, max_value=60, value=30, step=10)

        st.markdown("---")
        st.info("💡 **Tips:** Selain memilih halte dari menu di atas, Anda juga bisa langsung **mengklik titik mana saja** di dalam peta untuk menjadikan titik tersebut sebagai lokasi awal.")

    # --- 4. MANAJEMEN STATE (LOKASI AKTIF) ---
    # Default lokasi saat web pertama kali dibuka
    if 'lokasi_aktif' not in st.session_state:
        st.session_state['lokasi_aktif'] = halte_data["Halte Alun-Alun Bandung"]

    # Jika user memilih halte dari dropdown, perbarui lokasi aktif
    if pilihan_halte != "Pilih Halte / Lokasi Manual..." and halte_data[pilihan_halte] is not None:
        # Hanya update jika berbeda untuk menghindari looping refresh
        if st.session_state['lokasi_aktif'] != halte_data[pilihan_halte]:
            st.session_state['lokasi_aktif'] = halte_data[pilihan_halte]

    lat_awal, lon_awal = st.session_state['lokasi_aktif']

    # --- 5. RENDER PETA & ALGORITMA ---
    with col2:
        m = folium.Map(location=[lat_awal, lon_awal], zoom_start=13, tiles="CartoDB positron")

        with st.spinner('Mengkalkulasi jangkauan jaringan jalan...'):
            try:
                # Cari node jalan terdekat dari titik klik / halte
                center_node = ox.distance.nearest_nodes(G_final, X=lon_awal, Y=lat_awal)

                # Jalankan Dijkstra
                subgraph = nx.ego_graph(G_final, center_node, radius=waktu_maksimal, distance='waktu_tempuh')
                node_points = [Point((data['x'], data['y'])) for node, data in subgraph.nodes(data=True)]

                # Buat Poligon
                if len(node_points) > 3:
                    points_series = gpd.GeoSeries(node_points)
                    poligon = points_series.unary_union.convex_hull
                    simulasi_geojson = gpd.GeoDataFrame(index=[0], crs="EPSG:4326", geometry=[poligon])

                    folium.GeoJson(
                        simulasi_geojson,
                        style_function=lambda x: {'fillColor': '#2563eb', 'color': '#1e3a8a', 'weight': 2, 'fillOpacity': 0.4}
                    ).add_to(m)

                # Pasang Marker di lokasi aktif
                folium.Marker(
                    [lat_awal, lon_awal],
                    icon=folium.Icon(color="red", icon="map-marker")
                ).add_to(m)

            except Exception as e:
                st.warning(f"Titik ini terlalu jauh dari jaringan jalan (area kosong). Coba klik tempat lain. ({e})")

        # Tampilkan Peta dan Tangkap Klik User
        map_data = st_folium(m, width=900, height=550, key="isochrone_map_dynamic")

        # Logika: Jika pengguna MENGKLIK peta secara manual
        if map_data and map_data.get('last_clicked'):
            clicked_lat = map_data['last_clicked']['lat']
            clicked_lon = map_data['last_clicked']['lng']

            if (clicked_lat, clicked_lon) != st.session_state['lokasi_aktif']:
                st.session_state['lokasi_aktif'] = (clicked_lat, clicked_lon)
                st.rerun() # Refresh app untuk menghitung dari titik klik baru
